#include <Arduino.h>


/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/ddb5b299-3f31-4cd1-9061-4f4462e501dc 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  String test1;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/




int const potPin = A2; //Select analog ping A2
int dBread = 0;       // variable to store the value coming from the sensor
int dBlim = 0;  // variable to set the value in dB


void setupPotentiometer() 
{
  
}

void loopPotentiometer() {
  analogReadResolution(4); //Lower the resolution of the analog read. No need to use high resolution
  dBread = analogRead(potPin);    // read the value from the sensor - set the dB lim accordingly
 if (dBread <= 3)
 {
   dBlim = 50; 
 }
 else if (dBread <= 6)
 {
   dBlim = 60; 
 }
 else if (dBread <= 9)
 {
   dBlim = 70; 
 }
else if (dBread <= 12)
 {
   dBlim = 80; 
 }
 else
 {
   dBlim = 90; 
 }
Serial.println(dBlim); 
}