// Code generated by Arduino IoT Cloud, DO NOT EDIT.
#ifndef THINGPROPERTIES_H
#define THINGPROPERTIES_H

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char THING_ID[] = "ddb5b299-3f31-4cd1-9061-4f4462e501dc";

// // Mobile hotspot
// const char SSID[] = "DR licensvogn"; // Network SSID (name)
// const char PASS[] = "hemmeligkode";  // Network password (use for WPA, or use as key for WEP)
// // In-class router
const char SSID[] = "Arduino_router1";
const char PASS[] = "Y1_c0urse_r1";

void onDBBoundaryChange();
void onDBReadChange();
void onTest1Change();
void onTest2Change();
void onSleepValChange();

int dB_boundary;
int dB_read;
bool sleep_Val;

void initProperties()
{
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(dB_boundary, READWRITE, ON_CHANGE, onDBBoundaryChange);
  ArduinoCloud.addProperty(dB_read, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(sleep_Val, READWRITE, ON_CHANGE, onSleepValChange, 1);
}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
#endif